### ISSUE TITLE
Install the found Calendar gem and enable it on Cospace

### ISSUE THREAD

**Issue by ikigaidojo** [ikigaidojo/cospace#101]
- [x] install simple_calendar
- [x] get an understanding of it
- [x] create a calendar page and implement it

**Comment by Frothacker** [comment]
done, I think. We still need to transfer data when each day is clicked

**Comment by Frothacker** [comment]
no turns out it broke, I will create a new branch from current develop and start again

**Comment by Frothacker** [comment]
all done. Now we need a new issure that to make it work with AJAX, and fix styleing, athough thats more sprinkles.
