### ISSUE TITLE
Add "Resend confirmation" Link to the "Check your email" page

### ISSUE THREAD

**Issue by ikigaidojo** [ikigaidojo/cospace#172]

**Comment by hermanomark** [comment]
I'll do this!

**Comment by Frothacker** [comment]
Awesome! can you also make that page have boostrap styling? I can add my self if you to do that on too if you want.

**Comment by hermanomark** [comment]
I put some styling! but you can make it more fabulous if you want :)

**Comment by hermanomark** [comment]
this is done!
