### ISSUE TITLE
Instead of "Click a day to see available rooms" replace it instead by displaying the current available rooms for the current day

### ISSUE THREAD

**Issue by ikigaidojo** [ikigaidojo/cospace#186]

**Comment by ikigaidojo** [comment]
Instead of "Click a day to see available rooms" change it instead by displaying the current available rooms for the current day

**Comment by Frothacker** [comment]
he fix is done but it's not pretty: I hardcoded some sample HTML to take the place before Ajax is triggered. 
This is not optimal but still sufficient given that this is a very low priority issue, to the point of sprinkles
