### ISSUE TITLE
Remove the "Pending" test example in the event_attendee_spec.rb

### ISSUE THREAD

**Issue by ikigaidojo** [ikigaidojo/cospace#29]

**Comment by ikigaidojo** [comment]
Steps to do:

1. go to the  **develop** branch and do a git pull
2. create a new branch called task-#29
3. go to _spec\models\event_attendee_spec.rb_, and remove the Pending test example
4. Save. Do a **git add**. Do a **git commit**. Do a **git push**. Go got GitHub.com and **file a PR**.

**Comment by hermanomark** [comment]
this was already done, link of pr: https://github.com/ikigaidojo/cospace/pull/67/commits/219fd3da519a8be5b89d5cc3cf182c7f572f77d5
