### ISSUE TITLE
Enable code_coverage for cospace rails app

### ISSUE THREAD

**Issue by ikigaidojo** [ikigaidojo/cospace#41]
## To do's

- [x] install code_coverage gem [https://github.com/colszowka/simplecov](https://github.com/colszowka/simplecov))
- [x] enable the code_coverage for cospace rails app

## Notable Links
* [https://github.com/colszowka/simplecov](https://github.com/colszowka/simplecov)
* [https://medium.com/@RyanDavidson/display-your-ruby-test-coverage-using-simplecov-gem-and-codeclimate-6db6336fe409](https://medium.com/@RyanDavidson/display-your-ruby-test-coverage-using-simplecov-gem-and-codeclimate-6db6336fe409)

**Comment by hermanomark** [comment]
Going through it!

**Comment by ikigaidojo** [comment]
Done.
