### ISSUE TITLE
Establish association between Member and PaymentConfirmation model

### ISSUE THREAD

**Issue by ikigaidojo** [ikigaidojo/cospace#43]
## To do's

- [x] write an rspec test to confirm the association between Member and PaymentConfirmation Model
- [x] implement the association between the Member and PaymentConfirmation model

## Note
Member has_many PaymentConfirmation

**Comment by Frothacker** [comment]
Shoulda is installed. 
test is created and association confirmed for payment_confirmation  and member. Error due to association in the payment confirmation written as "belongs to :member", not "belongs_to :member"
