### ISSUE TITLE
Do a spike session and figure out how to install and enable Devise on cospace

### ISSUE THREAD

**Issue by ikigaidojo** [ikigaidojo/cospace#52]

**Comment by hermanomark** [comment]
trying to do it 🗡

**Comment by hermanomark** [comment]
notable link: https://github.com/plataformatec/devise

**Comment by Frothacker** [comment]
I did It! finally. I ended up creating a new branch called DeviseAttempt and had to learn about writing migrations in order to make devise migrate properly. Thank god. Also remembered to add the <%= yield %> inside application.html.erb
