### ISSUE TITLE
Implement the page that would be seen by the member once he or she logs in

### ISSUE THREAD

**Issue by ikigaidojo** [ikigaidojo/cospace#88]
- [ ] make sure that that said page is not accessible for non logged in members. Use the facility of Devise to accomplish this
- [ ] apply bootstrap styling

**Comment by hermanomark** [comment]
I think we should leave this open because we're still doing what's inside cospace after user logged in

**Comment by Frothacker** [comment]
all done, they are directed to the calendar page. also It ensures that member is logged in before that can access the calendar
