### ISSUE TITLE
Override the page for the member to sign up

### ISSUE THREAD

**Issue by ikigaidojo** [ikigaidojo/cospace#89]
- [x] override the existing code view used by Devise for signing up members
- [x] apply bootstrap styling
- [ ] add name field and make it work (modify model and controller)

**Comment by Frothacker** [comment]
doing :)

**Comment by Frothacker** [comment]
donskis :)

**Comment by Frothacker** [comment]
will figure out how to add name field and have it accepted by rails/devise

**Comment by Frothacker** [comment]
it works YEsssssss
